//
// auto-generated by op2.py
//

//user function
//user function
//#pragma acc routine
inline void CalcNewEStep3_openacc( double *e_new, const double *work) {
    e_new[0] += double(0.5) * work[0];

    if (fabs(e_new[0]) < m_e_cut) {
        e_new[0] = double(0.)  ;
    }
    if (     e_new[0]  < m_emin ) {
        e_new[0] = m_emin ;
    }
}

// host stub function
void op_par_loop_CalcNewEStep3(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  int nargs = 2;
  op_arg args[2];

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(23);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[23].name      = name;
  OP_kernels[23].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CalcNewEStep3");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1)
    for ( int n=0; n<set->size; n++ ){
      CalcNewEStep3_openacc(
        &data0[1*n],
        &data1[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[23].time     += wall_t2 - wall_t1;
  OP_kernels[23].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[23].transfer += (float)set->size * arg1.size;
}
