//
// auto-generated by op2.py
//

//user function
//user function
//#pragma acc routine
inline void CalcNewE_openacc( double *e_new, const double *e_old, const double *delvc, const double *p_old, const double *q_old, const double *work) {
    e_new[0] = e_old[0] - double(0.5) * delvc[0] * (p_old[0] + q_old[0])
        + double(0.5) * work[0];

    if (e_new[0]  < m_emin ) {
        e_new[0] = m_emin ;
    }
}

// host stub function
void op_par_loop_CalcNewE(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5){

  int nargs = 6;
  op_arg args[6];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(21);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[21].name      = name;
  OP_kernels[21].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CalcNewE");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    double* data2 = (double*)arg2.data_d;
    double* data3 = (double*)arg3.data_d;
    double* data4 = (double*)arg4.data_d;
    double* data5 = (double*)arg5.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1,data2,data3,data4,data5)
    for ( int n=0; n<set->size; n++ ){
      CalcNewE_openacc(
        &data0[1*n],
        &data1[1*n],
        &data2[1*n],
        &data3[1*n],
        &data4[1*n],
        &data5[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[21].time     += wall_t2 - wall_t1;
  OP_kernels[21].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[21].transfer += (float)set->size * arg1.size;
  OP_kernels[21].transfer += (float)set->size * arg2.size;
  OP_kernels[21].transfer += (float)set->size * arg3.size;
  OP_kernels[21].transfer += (float)set->size * arg4.size;
  OP_kernels[21].transfer += (float)set->size * arg5.size;
}
