//
// auto-generated by op2.py
//

//user function
//user function
//#pragma acc routine
inline void CalcHydroConstraint_openacc( const double *vdov, double *dthydro) {
    double dtdvov = m_dvovmax / (fabs(vdov[0])+double(1.e-20)) ;

    if ( (*dthydro) > dtdvov ) {
            (*dthydro) = dtdvov ;

    }
}

// host stub function
void op_par_loop_CalcHydroConstraint(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  double*arg1h = (double *)arg1.data;
  int nargs = 2;
  op_arg args[2];

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(39);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[39].name      = name;
  OP_kernels[39].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CalcHydroConstraint");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);

  double arg1_l = arg1h[0];

  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    #pragma acc parallel loop independent deviceptr(data0) reduction(min:arg1_l)
    for ( int n=0; n<set->size; n++ ){
      CalcHydroConstraint_openacc(
        &data0[1*n],
        &arg1_l);
    }
  }

  // combine reduction data
  arg1h[0]  = MIN(arg1h[0],arg1_l);
  op_mpi_reduce_double(&arg1,arg1h);
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[39].time     += wall_t2 - wall_t1;
  OP_kernels[39].transfer += (float)set->size * arg0.size;
}
