//
// auto-generated by op2.py
//

//user function
//user function
//#pragma acc routine
inline void CalcNewEStep2_openacc( const double *compHalfStep, const double *delvc, double *q_new, const double *pbvc, double *e_new, const double *bvc,
                            const double *pHalfStep, const double *ql_old, const double *qq_old, const double *p_old, const double *q_old
) {
    double vhalf = double(1.) / (double(1.) + compHalfStep[0]) ;

    if ( delvc[0] > double(0.) ) {
        q_new[0]  = double(0.) ;
    }
    else {
        double ssc = ( pbvc[0] * e_new[0]
                + vhalf * vhalf * bvc[0] * pHalfStep[0] ) / m_refdens ;

        if ( ssc <= m_ssc_thresh ) {
        ssc = m_ssc_low ;
        } else {
        ssc = sqrt(ssc) ;
        }

        q_new[0] = (ssc*ql_old[0] + qq_old[0]) ;
    }

    e_new[0] = e_new[0] + double(0.5) * delvc[0]
        * (  double(3.0)*(p_old[0]     + q_old[0])
            - double(4.0)*(pHalfStep[0] + q_new[0])) ;
}

// host stub function
void op_par_loop_CalcNewEStep2(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5,
  op_arg arg6,
  op_arg arg7,
  op_arg arg8,
  op_arg arg9,
  op_arg arg10){

  int nargs = 11;
  op_arg args[11];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;
  args[6] = arg6;
  args[7] = arg7;
  args[8] = arg8;
  args[9] = arg9;
  args[10] = arg10;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(22);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[22].name      = name;
  OP_kernels[22].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CalcNewEStep2");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    double* data2 = (double*)arg2.data_d;
    double* data3 = (double*)arg3.data_d;
    double* data4 = (double*)arg4.data_d;
    double* data5 = (double*)arg5.data_d;
    double* data6 = (double*)arg6.data_d;
    double* data7 = (double*)arg7.data_d;
    double* data8 = (double*)arg8.data_d;
    double* data9 = (double*)arg9.data_d;
    double* data10 = (double*)arg10.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1,data2,data3,data4,data5,data6,data7,data8,data9,data10)
    for ( int n=0; n<set->size; n++ ){
      CalcNewEStep2_openacc(
        &data0[1*n],
        &data1[1*n],
        &data2[1*n],
        &data3[1*n],
        &data4[1*n],
        &data5[1*n],
        &data6[1*n],
        &data7[1*n],
        &data8[1*n],
        &data9[1*n],
        &data10[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[22].time     += wall_t2 - wall_t1;
  OP_kernels[22].transfer += (float)set->size * arg0.size;
  OP_kernels[22].transfer += (float)set->size * arg1.size;
  OP_kernels[22].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[22].transfer += (float)set->size * arg3.size;
  OP_kernels[22].transfer += (float)set->size * arg4.size * 2.0f;
  OP_kernels[22].transfer += (float)set->size * arg5.size;
  OP_kernels[22].transfer += (float)set->size * arg6.size;
  OP_kernels[22].transfer += (float)set->size * arg7.size;
  OP_kernels[22].transfer += (float)set->size * arg8.size;
  OP_kernels[22].transfer += (float)set->size * arg9.size;
  OP_kernels[22].transfer += (float)set->size * arg10.size;
}
