//
// auto-generated by op2.py
//

//user function
//user function
//#pragma acc routine
inline void CopyTempEOSVarsBack_openacc( 
                                double *p, const double *p_new,
                                double *e, const double *e_new,
                                double *q, const double *q_new) {
    p[0] = p_new[0];
    e[0] = e_new[0];
    q[0] = q_new[0];
}

// host stub function
void op_par_loop_CopyTempEOSVarsBack(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5){

  int nargs = 6;
  op_arg args[6];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(32);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[32].name      = name;
  OP_kernels[32].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CopyTempEOSVarsBack");
  }

  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);


  if (set_size >0) {


    //Set up typed device pointers for OpenACC

    double* data0 = (double*)arg0.data_d;
    double* data1 = (double*)arg1.data_d;
    double* data2 = (double*)arg2.data_d;
    double* data3 = (double*)arg3.data_d;
    double* data4 = (double*)arg4.data_d;
    double* data5 = (double*)arg5.data_d;
    #pragma acc parallel loop independent deviceptr(data0,data1,data2,data3,data4,data5)
    for ( int n=0; n<set->size; n++ ){
      CopyTempEOSVarsBack_openacc(
        &data0[1*n],
        &data1[1*n],
        &data2[1*n],
        &data3[1*n],
        &data4[1*n],
        &data5[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit_cuda(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[32].time     += wall_t2 - wall_t1;
  OP_kernels[32].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[32].transfer += (float)set->size * arg1.size;
  OP_kernels[32].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[32].transfer += (float)set->size * arg3.size;
  OP_kernels[32].transfer += (float)set->size * arg4.size * 2.0f;
  OP_kernels[32].transfer += (float)set->size * arg5.size;
}
