//
// auto-generated by op2.py
//

//user function
#include "../CalcMonotonicQRegionForElem.h"

// host stub function
void op_par_loop_CalcMonotonicQRegionForElem(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5,
  op_arg arg6,
  op_arg arg7,
  op_arg arg8,
  op_arg arg9,
  op_arg arg10,
  op_arg arg11,
  op_arg arg12,
  op_arg arg13,
  op_arg arg14,
  op_arg arg15,
  op_arg arg16,
  op_arg arg17,
  op_arg arg18){

  int nargs = 19;
  op_arg args[19];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;
  args[6] = arg6;
  args[7] = arg7;
  args[8] = arg8;
  args[9] = arg9;
  args[10] = arg10;
  args[11] = arg11;
  args[12] = arg12;
  args[13] = arg13;
  args[14] = arg14;
  args[15] = arg15;
  args[16] = arg16;
  args[17] = arg17;
  args[18] = arg18;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(15);
  op_timers_core(&cpu_t1, &wall_t1);

  if (OP_diags>2) {
    printf(" kernel routine with indirection: CalcMonotonicQRegionForElem\n");
  }

  int set_size = op_mpi_halo_exchanges(set, nargs, args);

  if (set_size > 0) {

    for ( int n=0; n<set_size; n++ ){
      if (n<set->core_size && n>0 && n % OP_mpi_test_frequency == 0)
        op_mpi_test_all(nargs,args);
      if (n==set->core_size) {
        op_mpi_wait_all(nargs, args);
      }
      int map0idx;
      int map1idx;
      int map2idx;
      int map4idx;
      int map5idx;
      int map7idx;
      int map8idx;
      map0idx = arg0.map_data[n * arg0.map->dim + 0];
      map1idx = arg1.map_data[n * arg1.map->dim + 0];
      map2idx = arg2.map_data[n * arg2.map->dim + 0];
      map4idx = arg4.map_data[n * arg4.map->dim + 0];
      map5idx = arg5.map_data[n * arg5.map->dim + 0];
      map7idx = arg7.map_data[n * arg7.map->dim + 0];
      map8idx = arg8.map_data[n * arg8.map->dim + 0];


      CalcMonotonicQRegionForElem(
        &((double*)arg0.data)[1 * map0idx],
        &((double*)arg1.data)[1 * map1idx],
        &((double*)arg2.data)[1 * map2idx],
        &((double*)arg3.data)[1 * map0idx],
        &((double*)arg4.data)[1 * map4idx],
        &((double*)arg5.data)[1 * map5idx],
        &((double*)arg6.data)[1 * map0idx],
        &((double*)arg7.data)[1 * map7idx],
        &((double*)arg8.data)[1 * map8idx],
        &((double*)arg9.data)[1 * map0idx],
        &((double*)arg10.data)[1 * map0idx],
        &((double*)arg11.data)[1 * map0idx],
        &((int*)arg12.data)[1 * map0idx],
        &((double*)arg13.data)[1 * map0idx],
        &((double*)arg14.data)[1 * map0idx],
        &((double*)arg15.data)[1 * map0idx],
        &((double*)arg16.data)[1 * map0idx],
        &((double*)arg17.data)[1 * map0idx],
        &((double*)arg18.data)[1 * map0idx]);
    }
  }

  if (set_size == 0 || set_size == set->core_size) {
    op_mpi_wait_all(nargs, args);
  }
  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[15].name      = name;
  OP_kernels[15].count    += 1;
  OP_kernels[15].time     += wall_t2 - wall_t1;
  OP_kernels[15].transfer += (float)set->size * arg0.size;
  OP_kernels[15].transfer += (float)set->size * arg3.size;
  OP_kernels[15].transfer += (float)set->size * arg6.size;
  OP_kernels[15].transfer += (float)set->size * arg9.size;
  OP_kernels[15].transfer += (float)set->size * arg10.size;
  OP_kernels[15].transfer += (float)set->size * arg11.size;
  OP_kernels[15].transfer += (float)set->size * arg12.size;
  OP_kernels[15].transfer += (float)set->size * arg13.size;
  OP_kernels[15].transfer += (float)set->size * arg14.size;
  OP_kernels[15].transfer += (float)set->size * arg15.size;
  OP_kernels[15].transfer += (float)set->size * arg16.size;
  OP_kernels[15].transfer += (float)set->size * arg17.size;
  OP_kernels[15].transfer += (float)set->size * arg18.size;
  OP_kernels[15].transfer += (float)set->size * arg0.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg1.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg2.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg4.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg5.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg7.map->dim * 4.0f;
  OP_kernels[15].transfer += (float)set->size * arg8.map->dim * 4.0f;
}
