//
// auto-generated by op2.py
//

void CalcPosForNodes_omp4_kernel(
  double *data0,
  int dat0size,
  double *data1,
  int dat1size,
  double *data2,
  int dat2size,
  double *data3,
  int dat3size,
  double *data4,
  int dat4size,
  double *data5,
  int dat5size,
  double *arg6,
  int count,
  int num_teams,
  int nthread){

  double arg6_l = *arg6;
  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data0[0:dat0size],data1[0:dat1size],data2[0:dat2size],data3[0:dat3size],data4[0:dat4size],data5[0:dat5size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int n_op=0; n_op<count; n_op++ ){
    //variable mapping
    double *x = &data0[1*n_op];
    double *y = &data1[1*n_op];
    double *z = &data2[1*n_op];
    const double *xd = &data3[1*n_op];
    const double *yd = &data4[1*n_op];
    const double *zd = &data5[1*n_op];
    const double *dt = &arg6_l;

    //inline function
    
      x[0] += xd[0] * (*dt) ;
      y[0] += yd[0] * (*dt) ;
      z[0] += zd[0] * (*dt) ;
    //end inline func
  }

  *arg6 = arg6_l;
}
