//
// auto-generated by op2.py
//

void CalcHydroConstraint_omp4_kernel(
  int *map0,
  int map0size,
  double *arg1,
  double *data0,
  int dat0size,
  int *col_reord,
  int set_size1,
  int start,
  int end,
  int num_teams,
  int nthread){

  double arg1_l = *arg1;
  #pragma omp target teams num_teams(num_teams) thread_limit(nthread)  \
    map(to: m_dvovmax_ompkernel)\
    map(to:col_reord[0:set_size1],map0[0:map0size],data0[0:dat0size])\
    map(tofrom: arg1_l) reduction(min:arg1_l)
  #pragma omp distribute parallel for schedule(static,1) reduction(min:arg1_l)
  for ( int e=start; e<end; e++ ){
    int n_op = col_reord[e];
    int map0idx;
    map0idx = map0[n_op + set_size1 * 0];

    //variable mapping
    const double *vdov = &data0[1 * map0idx];
    double *dthydro = &arg1_l;

    //inline function
    
      double dtdvov = m_dvovmax_ompkernel / (fabs(vdov[0])+double(1.e-20)) ;

      if ( (*dthydro) > dtdvov ) {
              (*dthydro) = dtdvov ;

      }
    //end inline func
  }

  *arg1 = arg1_l;
}
