//
// auto-generated by op2.py
//

//user function
inline void ALE3DRelevantCheck(const double *v){
    double vc = v[0] ;
    
    if (m_eosvmin != double(0.)) {
        if (vc < m_eosvmin)
        vc = m_eosvmin ;
    }
    if (m_eosvmax != double(0.)) {
        if (vc > m_eosvmax)
        vc = m_eosvmax ;
    }
    if (vc <= 0.) {
        // exit(-1); // Volume Error
    }
}

// host stub function
void op_par_loop_ALE3DRelevantCheck(char const *name, op_set set,
  op_arg arg0){

  int nargs = 1;
  op_arg args[1];

  args[0] = arg0;
  //create aligned pointers for dats
  ALIGNED_double const double * __restrict__ ptr0 = (double *) arg0.data;
  DECLARE_PTR_ALIGNED(ptr0,double_ALIGN);

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(36);
  op_timers_core(&cpu_t1, &wall_t1);


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  ALE3DRelevantCheck");
  }

  int exec_size = op_mpi_halo_exchanges(set, nargs, args);

  if (exec_size >0) {

    #ifdef VECTORIZE
    #pragma novector
    for ( int n=0; n<(exec_size/SIMD_VEC)*SIMD_VEC; n+=SIMD_VEC ){
      #pragma omp simd simdlen(SIMD_VEC)
      for ( int i=0; i<SIMD_VEC; i++ ){
        ALE3DRelevantCheck(
          &(ptr0)[1 * (n+i)]);
      }
    }
    //remainder
    for ( int n=(exec_size/SIMD_VEC)*SIMD_VEC; n<exec_size; n++ ){
    #else
    for ( int n=0; n<exec_size; n++ ){
    #endif
      ALE3DRelevantCheck(
        &(ptr0)[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[36].name      = name;
  OP_kernels[36].count    += 1;
  OP_kernels[36].time     += wall_t2 - wall_t1;
  OP_kernels[36].transfer += (float)set->size * arg0.size;
}
