//
// auto-generated by op2.py
//

//user function
inline void CopyEOSValsIntoArray(
                                double *e_old, const double *e,
                                double *delvc, const double *delv,
                                double *p_old, const double *p,
                                double *q_old, const double *q,
                                double *qq_old, const double *qq,
                                double *ql_old, const double *ql){
    e_old[0] = e[0] ;
    delvc[0] = delv[0] ;
    
    p_old[0] = p[0] ;
    q_old[0] = q[0] ;

    qq_old[0] = qq[0] ;
    ql_old[0] = ql[0] ;
}

// host stub function
void op_par_loop_CopyEOSValsIntoArray(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5,
  op_arg arg6,
  op_arg arg7,
  op_arg arg8,
  op_arg arg9,
  op_arg arg10,
  op_arg arg11){

  int nargs = 12;
  op_arg args[12];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;
  args[6] = arg6;
  args[7] = arg7;
  args[8] = arg8;
  args[9] = arg9;
  args[10] = arg10;
  args[11] = arg11;
  //create aligned pointers for dats
  ALIGNED_double       double * __restrict__ ptr0 = (double *) arg0.data;
  DECLARE_PTR_ALIGNED(ptr0,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr1 = (double *) arg1.data;
  DECLARE_PTR_ALIGNED(ptr1,double_ALIGN);
  ALIGNED_double       double * __restrict__ ptr2 = (double *) arg2.data;
  DECLARE_PTR_ALIGNED(ptr2,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr3 = (double *) arg3.data;
  DECLARE_PTR_ALIGNED(ptr3,double_ALIGN);
  ALIGNED_double       double * __restrict__ ptr4 = (double *) arg4.data;
  DECLARE_PTR_ALIGNED(ptr4,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr5 = (double *) arg5.data;
  DECLARE_PTR_ALIGNED(ptr5,double_ALIGN);
  ALIGNED_double       double * __restrict__ ptr6 = (double *) arg6.data;
  DECLARE_PTR_ALIGNED(ptr6,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr7 = (double *) arg7.data;
  DECLARE_PTR_ALIGNED(ptr7,double_ALIGN);
  ALIGNED_double       double * __restrict__ ptr8 = (double *) arg8.data;
  DECLARE_PTR_ALIGNED(ptr8,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr9 = (double *) arg9.data;
  DECLARE_PTR_ALIGNED(ptr9,double_ALIGN);
  ALIGNED_double       double * __restrict__ ptr10 = (double *) arg10.data;
  DECLARE_PTR_ALIGNED(ptr10,double_ALIGN);
  ALIGNED_double const double * __restrict__ ptr11 = (double *) arg11.data;
  DECLARE_PTR_ALIGNED(ptr11,double_ALIGN);

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(27);
  op_timers_core(&cpu_t1, &wall_t1);


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CopyEOSValsIntoArray");
  }

  int exec_size = op_mpi_halo_exchanges(set, nargs, args);

  if (exec_size >0) {

    #ifdef VECTORIZE
    #pragma novector
    for ( int n=0; n<(exec_size/SIMD_VEC)*SIMD_VEC; n+=SIMD_VEC ){
      #pragma omp simd simdlen(SIMD_VEC)
      for ( int i=0; i<SIMD_VEC; i++ ){
        CopyEOSValsIntoArray(
          &(ptr0)[1 * (n+i)],
          &(ptr1)[1 * (n+i)],
          &(ptr2)[1 * (n+i)],
          &(ptr3)[1 * (n+i)],
          &(ptr4)[1 * (n+i)],
          &(ptr5)[1 * (n+i)],
          &(ptr6)[1 * (n+i)],
          &(ptr7)[1 * (n+i)],
          &(ptr8)[1 * (n+i)],
          &(ptr9)[1 * (n+i)],
          &(ptr10)[1 * (n+i)],
          &(ptr11)[1 * (n+i)]);
      }
    }
    //remainder
    for ( int n=(exec_size/SIMD_VEC)*SIMD_VEC; n<exec_size; n++ ){
    #else
    for ( int n=0; n<exec_size; n++ ){
    #endif
      CopyEOSValsIntoArray(
        &(ptr0)[1*n],
        &(ptr1)[1*n],
        &(ptr2)[1*n],
        &(ptr3)[1*n],
        &(ptr4)[1*n],
        &(ptr5)[1*n],
        &(ptr6)[1*n],
        &(ptr7)[1*n],
        &(ptr8)[1*n],
        &(ptr9)[1*n],
        &(ptr10)[1*n],
        &(ptr11)[1*n]);
    }
  }

  // combine reduction data
  op_mpi_set_dirtybit(nargs, args);

  // update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[27].name      = name;
  OP_kernels[27].count    += 1;
  OP_kernels[27].time     += wall_t2 - wall_t1;
  OP_kernels[27].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg1.size;
  OP_kernels[27].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg3.size;
  OP_kernels[27].transfer += (float)set->size * arg4.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg5.size;
  OP_kernels[27].transfer += (float)set->size * arg6.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg7.size;
  OP_kernels[27].transfer += (float)set->size * arg8.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg9.size;
  OP_kernels[27].transfer += (float)set->size * arg10.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg11.size;
}
