//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

// global constants
extern double m_e_cut;
extern double m_p_cut;
extern double m_q_cut;
extern double m_v_cut;
extern double m_u_cut;
extern double m_hgcoef;
extern double m_ss4o3;
extern double m_qstop;
extern double m_monoq_max_slope;
extern double m_monoq_limiter_mult;
extern double m_qlc_monoq;
extern double m_qqc_monoq;
extern double m_qqc;
extern double m_eosvmax;
extern double m_eosvmin;
extern double m_pmin;
extern double m_emin;
extern double m_dvovmax;
extern double m_refdens;
extern double m_qqc2;
extern double m_ptiny;
extern double m_gamma_t[32];
extern double m_twelfth;
extern double m_sixth;
extern double m_c1s;
extern double m_ssc_thresh;
extern double m_ssc_low;

// header
#include "op_lib_cpp.h"

// user kernel files
#include "initStressTerms_kernel.cpp"
#include "IntegrateStressForElemsLoop_kernel.cpp"
#include "FBHourglassForceForElems_kernel.cpp"
#include "CalcVolumeDerivatives_kernel.cpp"
#include "CheckForNegativeElementVolume_kernel.cpp"
#include "setForceToZero_kernel.cpp"
#include "CalcAccelForNodes_kernel.cpp"
#include "BoundaryX_kernel.cpp"
#include "BoundaryY_kernel.cpp"
#include "BoundaryZ_kernel.cpp"
#include "CalcVeloForNodes_kernel.cpp"
#include "CalcPosForNodes_kernel.cpp"
#include "CalcKinematicsForElem_kernel.cpp"
#include "CalcLagrangeElemRemaining_kernel.cpp"
#include "CalcMonotonicQGradientsForElem_kernel.cpp"
#include "CalcMonotonicQRegionForElem_kernel.cpp"
#include "NoExcessiveArtificialViscosity_kernel.cpp"
#include "CalcHalfStepBVC_kernel.cpp"
#include "CalcPHalfstep_kernel.cpp"
#include "CalcBVC_kernel.cpp"
#include "CalcPNew_kernel.cpp"
#include "CalcNewE_kernel.cpp"
#include "CalcNewEStep2_kernel.cpp"
#include "CalcNewEStep3_kernel.cpp"
#include "CalcNewEStep4_kernel.cpp"
#include "CalcQNew_kernel.cpp"
#include "CalcSoundSpeedForElem_kernel.cpp"
#include "CopyEOSValsIntoArray_kernel.cpp"
#include "CalcHalfSteps_kernel.cpp"
#include "CheckEOSLowerBound_kernel.cpp"
#include "CheckEOSUpperBound_kernel.cpp"
#include "CalcEOSWork_kernel.cpp"
#include "CopyTempEOSVarsBack_kernel.cpp"
#include "CopyVelocityToTempArray_kernel.cpp"
#include "ApplyLowerBoundToVelocity_kernel.cpp"
#include "ApplyUpperBoundToVelocity_kernel.cpp"
#include "ALE3DRelevantCheck_kernel.cpp"
#include "updateVolumesForElem_kernel.cpp"
#include "CalcCourantConstraint_kernel.cpp"
#include "CalcHydroConstraint_kernel.cpp"
#include "CalcSpeed_kernel.cpp"
