//
// auto-generated by op2.py
//

//user function
__device__ void CalcCourantConstraint_gpu( const double *ss, const double *vdov, const double *arealg, double *dtcourant) {

    double dtf = ss[0] * ss[0];

    if ( vdov[0] < double(0.) ) {

        dtf = dtf
            + m_qqc2_cuda * arealg[0] * arealg[0]
            * vdov[0] * vdov[0] ;
    }

    dtf = sqrt(dtf) ;

    dtf = arealg[0] / dtf ;

    if (vdov[0] != double(0.)) {
        if ( dtf < (*dtcourant) ) {
        (*dtcourant) = dtf ;

        }
    }

}

// CUDA kernel function
__global__ void op_cuda_CalcCourantConstraint(
  const double *__restrict ind_arg0,
  const double *__restrict ind_arg1,
  const double *__restrict ind_arg2,
  const int *__restrict opDat0Map,
  double *arg3,
  int start,
  int end,
  int   set_size) {
  double arg3_l[1];
  for ( int d=0; d<1; d++ ){
    arg3_l[d]=arg3[d+blockIdx.x*1];
  }
  int tid = threadIdx.x + blockIdx.x * blockDim.x;
  if (tid + start < end) {
    int n = tid + start;
    //initialise local variables
    int map0idx;
    map0idx = opDat0Map[n + set_size * 0];

    //user-supplied kernel call
    CalcCourantConstraint_gpu(ind_arg0+map0idx*1,
                          ind_arg1+map0idx*1,
                          ind_arg2+map0idx*1,
                          arg3_l);
  }

  //global reductions

  for ( int d=0; d<1; d++ ){
    op_reduction<OP_MIN>(&arg3[d+blockIdx.x*1],arg3_l[d]);
  }
}


//host stub function
void op_par_loop_CalcCourantConstraint(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3){

  double*arg3h = (double *)arg3.data;
  int nargs = 4;
  op_arg args[4];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(38);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[38].name      = name;
  OP_kernels[38].count    += 1;


  int    ninds   = 3;
  int    inds[4] = {0,1,2,-1};

  if (OP_diags>2) {
    printf(" kernel routine with indirection: CalcCourantConstraint\n");
  }
  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_38
      int nthread = OP_BLOCK_SIZE_38;
    #else
      int nthread = OP_block_size;
    #endif

    //transfer global reduction data to GPU
    int maxblocks = (MAX(set->core_size, set->size+set->exec_size-set->core_size)-1)/nthread+1;
    int reduct_bytes = 0;
    int reduct_size  = 0;
    reduct_bytes += ROUND_UP(maxblocks*1*sizeof(double));
    reduct_size   = MAX(reduct_size,sizeof(double));
    reallocReductArrays(reduct_bytes);
    reduct_bytes = 0;
    arg3.data   = OP_reduct_h + reduct_bytes;
    arg3.data_d = OP_reduct_d + reduct_bytes;
    for ( int b=0; b<maxblocks; b++ ){
      for ( int d=0; d<1; d++ ){
        ((double *)arg3.data)[d+b*1] = arg3h[d];
      }
    }
    reduct_bytes += ROUND_UP(maxblocks*1*sizeof(double));
    mvReductArraysToDevice(reduct_bytes);

    for ( int round=0; round<3; round++ ){
      if (round==1) {
        op_mpi_wait_all_grouped(nargs, args, 2);
      }
      int start = round==0 ? 0 : (round==1 ? set->core_size : set->size);
      int end = round==0 ? set->core_size : (round==1? set->size :  set->size + set->exec_size);
      if (end-start>0) {
        int nblocks = (end-start-1)/nthread+1;
        int nshared = reduct_size*nthread;
        op_cuda_CalcCourantConstraint<<<nblocks,nthread,nshared>>>(
        (double *)arg0.data_d,
        (double *)arg1.data_d,
        (double *)arg2.data_d,
        arg0.map_data_d,
        (double*)arg3.data_d,
        start,end,set->size+set->exec_size);
      }
      if (round==1) mvReductArraysToHost(reduct_bytes);
    }
    for ( int b=0; b<maxblocks; b++ ){
      for ( int d=0; d<1; d++ ){
        arg3h[d] = MIN(arg3h[d],((double *)arg3.data)[d+b*1]);
      }
    }
    arg3.data = (char *)arg3h;
    op_mpi_reduce(&arg3,arg3h);
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[38].time     += wall_t2 - wall_t1;
}
