//
// auto-generated by op2.py
//

//user function
__device__ void CalcHydroConstraint_gpu( const double *vdov, double *dthydro) {
    double dtdvov = m_dvovmax_cuda / (fabs(vdov[0])+double(1.e-20)) ;

    if ( (*dthydro) > dtdvov ) {
            (*dthydro) = dtdvov ;

    }

}

// CUDA kernel function
__global__ void op_cuda_CalcHydroConstraint(
  const double *__restrict ind_arg0,
  const int *__restrict opDat0Map,
  double *arg1,
  int start,
  int end,
  int   set_size) {
  double arg1_l[1];
  for ( int d=0; d<1; d++ ){
    arg1_l[d]=arg1[d+blockIdx.x*1];
  }
  int tid = threadIdx.x + blockIdx.x * blockDim.x;
  if (tid + start < end) {
    int n = tid + start;
    //initialise local variables
    int map0idx;
    map0idx = opDat0Map[n + set_size * 0];

    //user-supplied kernel call
    CalcHydroConstraint_gpu(ind_arg0+map0idx*1,
                        arg1_l);
  }

  //global reductions

  for ( int d=0; d<1; d++ ){
    op_reduction<OP_MIN>(&arg1[d+blockIdx.x*1],arg1_l[d]);
  }
}


//host stub function
void op_par_loop_CalcHydroConstraint(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1){

  double*arg1h = (double *)arg1.data;
  int nargs = 2;
  op_arg args[2];

  args[0] = arg0;
  args[1] = arg1;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(39);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[39].name      = name;
  OP_kernels[39].count    += 1;


  int    ninds   = 1;
  int    inds[2] = {0,-1};

  if (OP_diags>2) {
    printf(" kernel routine with indirection: CalcHydroConstraint\n");
  }
  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_39
      int nthread = OP_BLOCK_SIZE_39;
    #else
      int nthread = OP_block_size;
    #endif

    //transfer global reduction data to GPU
    int maxblocks = (MAX(set->core_size, set->size+set->exec_size-set->core_size)-1)/nthread+1;
    int reduct_bytes = 0;
    int reduct_size  = 0;
    reduct_bytes += ROUND_UP(maxblocks*1*sizeof(double));
    reduct_size   = MAX(reduct_size,sizeof(double));
    reallocReductArrays(reduct_bytes);
    reduct_bytes = 0;
    arg1.data   = OP_reduct_h + reduct_bytes;
    arg1.data_d = OP_reduct_d + reduct_bytes;
    for ( int b=0; b<maxblocks; b++ ){
      for ( int d=0; d<1; d++ ){
        ((double *)arg1.data)[d+b*1] = arg1h[d];
      }
    }
    reduct_bytes += ROUND_UP(maxblocks*1*sizeof(double));
    mvReductArraysToDevice(reduct_bytes);

    for ( int round=0; round<3; round++ ){
      if (round==1) {
        op_mpi_wait_all_grouped(nargs, args, 2);
      }
      int start = round==0 ? 0 : (round==1 ? set->core_size : set->size);
      int end = round==0 ? set->core_size : (round==1? set->size :  set->size + set->exec_size);
      if (end-start>0) {
        int nblocks = (end-start-1)/nthread+1;
        int nshared = reduct_size*nthread;
        op_cuda_CalcHydroConstraint<<<nblocks,nthread,nshared>>>(
        (double *)arg0.data_d,
        arg0.map_data_d,
        (double*)arg1.data_d,
        start,end,set->size+set->exec_size);
      }
      if (round==1) mvReductArraysToHost(reduct_bytes);
    }
    for ( int b=0; b<maxblocks; b++ ){
      for ( int d=0; d<1; d++ ){
        arg1h[d] = MIN(arg1h[d],((double *)arg1.data)[d+b*1]);
      }
    }
    arg1.data = (char *)arg1h;
    op_mpi_reduce(&arg1,arg1h);
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[39].time     += wall_t2 - wall_t1;
}
