//
// auto-generated by op2.py
//

//user function
__device__ void CheckEOSUpperBound_gpu( const double *vnewc, double *compHalfStep, double *compression, double* p_old) {
    if (vnewc[0] >= m_eosvmax_cuda) {
        p_old[0]        = double(0.) ;
        compression[0]  = double(0.) ;
        compHalfStep[0] = double(0.) ;
    }

}

// CUDA kernel function
__global__ void op_cuda_CheckEOSUpperBound(
  const double *__restrict arg0,
  double *arg1,
  double *arg2,
  double *arg3,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){

    //user-supplied kernel call
    CheckEOSUpperBound_gpu(arg0+n*1,
                       arg1+n*1,
                       arg2+n*1,
                       arg3+n*1);
  }
}


//host stub function
void op_par_loop_CheckEOSUpperBound(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3){

  int nargs = 4;
  op_arg args[4];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(30);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[30].name      = name;
  OP_kernels[30].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CheckEOSUpperBound");
  }

  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_30
      int nthread = OP_BLOCK_SIZE_30;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    op_cuda_CheckEOSUpperBound<<<nblocks,nthread>>>(
      (double *) arg0.data_d,
      (double *) arg1.data_d,
      (double *) arg2.data_d,
      (double *) arg3.data_d,
      set->size );
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[30].time     += wall_t2 - wall_t1;
  OP_kernels[30].transfer += (float)set->size * arg0.size;
  OP_kernels[30].transfer += (float)set->size * arg1.size * 2.0f;
  OP_kernels[30].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[30].transfer += (float)set->size * arg3.size * 2.0f;
}
