//
// auto-generated by op2.py
//

//user function
__device__ void CopyEOSValsIntoArray_gpu( 
                                double *e_old, const double *e,
                                double *delvc, const double *delv,
                                double *p_old, const double *p,
                                double *q_old, const double *q,
                                double *qq_old, const double *qq,
                                double *ql_old, const double *ql) {
    e_old[0] = e[0] ;
    delvc[0] = delv[0] ;

    p_old[0] = p[0] ;
    q_old[0] = q[0] ;

    qq_old[0] = qq[0] ;
    ql_old[0] = ql[0] ;

}

// CUDA kernel function
__global__ void op_cuda_CopyEOSValsIntoArray(
  double *arg0,
  const double *__restrict arg1,
  double *arg2,
  const double *__restrict arg3,
  double *arg4,
  const double *__restrict arg5,
  double *arg6,
  const double *__restrict arg7,
  double *arg8,
  const double *__restrict arg9,
  double *arg10,
  const double *__restrict arg11,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){

    //user-supplied kernel call
    CopyEOSValsIntoArray_gpu(arg0+n*1,
                         arg1+n*1,
                         arg2+n*1,
                         arg3+n*1,
                         arg4+n*1,
                         arg5+n*1,
                         arg6+n*1,
                         arg7+n*1,
                         arg8+n*1,
                         arg9+n*1,
                         arg10+n*1,
                         arg11+n*1);
  }
}


//host stub function
void op_par_loop_CopyEOSValsIntoArray(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4,
  op_arg arg5,
  op_arg arg6,
  op_arg arg7,
  op_arg arg8,
  op_arg arg9,
  op_arg arg10,
  op_arg arg11){

  int nargs = 12;
  op_arg args[12];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;
  args[5] = arg5;
  args[6] = arg6;
  args[7] = arg7;
  args[8] = arg8;
  args[9] = arg9;
  args[10] = arg10;
  args[11] = arg11;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(27);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[27].name      = name;
  OP_kernels[27].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  CopyEOSValsIntoArray");
  }

  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_27
      int nthread = OP_BLOCK_SIZE_27;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    op_cuda_CopyEOSValsIntoArray<<<nblocks,nthread>>>(
      (double *) arg0.data_d,
      (double *) arg1.data_d,
      (double *) arg2.data_d,
      (double *) arg3.data_d,
      (double *) arg4.data_d,
      (double *) arg5.data_d,
      (double *) arg6.data_d,
      (double *) arg7.data_d,
      (double *) arg8.data_d,
      (double *) arg9.data_d,
      (double *) arg10.data_d,
      (double *) arg11.data_d,
      set->size );
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[27].time     += wall_t2 - wall_t1;
  OP_kernels[27].transfer += (float)set->size * arg0.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg1.size;
  OP_kernels[27].transfer += (float)set->size * arg2.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg3.size;
  OP_kernels[27].transfer += (float)set->size * arg4.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg5.size;
  OP_kernels[27].transfer += (float)set->size * arg6.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg7.size;
  OP_kernels[27].transfer += (float)set->size * arg8.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg9.size;
  OP_kernels[27].transfer += (float)set->size * arg10.size * 2.0f;
  OP_kernels[27].transfer += (float)set->size * arg11.size;
}
